/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.12
 * Generated at: 2024-10-07 08:14:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import LapTrinhWeb_Cha.models.UserModel;
import LapTrinhWeb_Cha.controllers.WaitingController;

public final class login_005fsuccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("LapTrinhWeb_Cha.controllers.WaitingController");
    _jspx_imports_classes.add("LapTrinhWeb_Cha.models.UserModel");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Start Top Nav -->\r\n");
      out.write("	<nav\r\n");
      out.write("		class=\"navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block\"\r\n");
      out.write("		id=\"templatemo_nav_top\">\r\n");
      out.write("		<div class=\"container text-light\">\r\n");
      out.write("			<div class=\"w-100 d-flex justify-content-between\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<i class=\"fa fa-envelope mx-2\"></i> <a\r\n");
      out.write("						class=\"navbar-sm-brand text-light text-decoration-none\"\r\n");
      out.write("						href=\"mailto:info@company.com\">info@company.com</a> <i\r\n");
      out.write("						class=\"fa fa-phone mx-2\"></i> <a\r\n");
      out.write("						class=\"navbar-sm-brand text-light text-decoration-none\"\r\n");
      out.write("						href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<a class=\"text-light\" href=\"https://fb.com/templatemo\"\r\n");
      out.write("						target=\"_blank\" rel=\"sponsored\"><i\r\n");
      out.write("						class=\"fab fa-facebook-f fa-sm fa-fw me-2\"></i></a> <a\r\n");
      out.write("						class=\"text-light\" href=\"https://www.instagram.com/\"\r\n");
      out.write("						target=\"_blank\"><i class=\"fab fa-instagram fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("					<a class=\"text-light\" href=\"https://twitter.com/\" target=\"_blank\"><i\r\n");
      out.write("						class=\"fab fa-twitter fa-sm fa-fw me-2\"></i></a> <a class=\"text-light\"\r\n");
      out.write("						href=\"https://www.linkedin.com/\" target=\"_blank\"><i\r\n");
      out.write("						class=\"fab fa-linkedin fa-sm fa-fw\"></i></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- Close Top Nav -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade bg-white\" id=\"templatemo_search\" tabindex=\"-1\"\r\n");
      out.write("		role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("			<div class=\"w-100 pt-1 mb-5 text-right\">\r\n");
      out.write("				<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("					aria-label=\"Close\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form action=\"\" method=\"get\"\r\n");
      out.write("				class=\"modal-content modal-body border-0 p-0\">\r\n");
      out.write("				<div class=\"input-group mb-2\">\r\n");
      out.write("					<input type=\"text\" class=\"form-control\" id=\"inputModalSearch\"\r\n");
      out.write("						name=\"q\" placeholder=\"Search ...\">\r\n");
      out.write("					<button type=\"submit\"\r\n");
      out.write("						class=\"input-group-text bg-success text-light\">\r\n");
      out.write("						<i class=\"fa fa-fw fa-search text-white\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Banner Hero -->\r\n");
      out.write("	<div id=\"template-mo-zay-hero-carousel\" class=\"carousel slide\"\r\n");
      out.write("		data-bs-ride=\"carousel\">\r\n");
      out.write("		<ol class=\"carousel-indicators\">\r\n");
      out.write("			<li data-bs-target=\"#template-mo-zay-hero-carousel\"\r\n");
      out.write("				data-bs-slide-to=\"0\" class=\"\"></li>\r\n");
      out.write("			<li data-bs-target=\"#template-mo-zay-hero-carousel\"\r\n");
      out.write("				data-bs-slide-to=\"1\" class=\"\"></li>\r\n");
      out.write("			<li data-bs-target=\"#template-mo-zay-hero-carousel\"\r\n");
      out.write("				data-bs-slide-to=\"2\" class=\"active\"></li>\r\n");
      out.write("		</ol>\r\n");
      out.write("		<div class=\"carousel-inner\">\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row p-5\">\r\n");
      out.write("						<div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("							<img class=\"img-fluid\"\r\n");
      out.write("								src=\"templates/web/assets/img/banner_img_01.jpg\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("							<div class=\"text-align-left align-self-center\">\r\n");
      out.write("								<h1 class=\"h1 text-success\">\r\n");
      out.write("									<b>Zay</b> eCommerce\r\n");
      out.write("								</h1>\r\n");
      out.write("								<h3 class=\"h2\">Tiny and Perfect eCommerce Template</h3>\r\n");
      out.write("								<p>\r\n");
      out.write("									Zay Shop is an eCommerce HTML5 CSS template with latest version\r\n");
      out.write("									of Bootstrap 5 (beta 1). This template is 100% free provided by\r\n");
      out.write("									<a rel=\"sponsored\" class=\"text-success\"\r\n");
      out.write("										href=\"https://templatemo.com\" target=\"_blank\">TemplateMo</a>\r\n");
      out.write("									website. Image credits go to <a rel=\"sponsored\"\r\n");
      out.write("										class=\"text-success\" href=\"https://stories.freepik.com/\"\r\n");
      out.write("										target=\"_blank\">Freepik Stories</a>, <a rel=\"sponsored\"\r\n");
      out.write("										class=\"text-success\" href=\"https://unsplash.com/\"\r\n");
      out.write("										target=\"_blank\">Unsplash</a> and <a rel=\"sponsored\"\r\n");
      out.write("										class=\"text-success\" href=\"https://icons8.com/\"\r\n");
      out.write("										target=\"_blank\">Icons 8</a>.\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row p-5\">\r\n");
      out.write("						<div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("							<img class=\"img-fluid\"\r\n");
      out.write("								src=\"templates/web/assets/img/banner_img_02.jpg\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("							<div class=\"text-align-left\">\r\n");
      out.write("								<h1 class=\"h1\">Proident occaecat</h1>\r\n");
      out.write("								<h3 class=\"h2\">Aliquip ex ea commodo consequat</h3>\r\n");
      out.write("								<p>\r\n");
      out.write("									You are permitted to use this Zay CSS template for your\r\n");
      out.write("									commercial websites. You are <strong>not permitted</strong> to\r\n");
      out.write("									re-distribute the template ZIP file in any kind of template\r\n");
      out.write("									collection websites.\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item active\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row p-5\">\r\n");
      out.write("						<div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("							<img class=\"img-fluid\"\r\n");
      out.write("								src=\"templates/web/assets/img/banner_img_03.jpg\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("							<div class=\"text-align-left\">\r\n");
      out.write("								<h1 class=\"h1\">Repr in voluptate</h1>\r\n");
      out.write("								<h3 class=\"h2\">Ullamco laboris nisi ut</h3>\r\n");
      out.write("								<p>We bring you 100% free CSS templates for your websites.\r\n");
      out.write("									If you wish to support TemplateMo, please make a small\r\n");
      out.write("									contribution via PayPal or tell your friends about our website.\r\n");
      out.write("									Thank you.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<a class=\"carousel-control-prev text-decoration-none w-auto ps-3\"\r\n");
      out.write("			href=\"#template-mo-zay-hero-carousel\" role=\"button\"\r\n");
      out.write("			data-bs-slide=\"prev\"> <i class=\"fas fa-chevron-left\"></i>\r\n");
      out.write("		</a> <a class=\"carousel-control-next text-decoration-none w-auto pe-3\"\r\n");
      out.write("			href=\"#template-mo-zay-hero-carousel\" role=\"button\"\r\n");
      out.write("			data-bs-slide=\"next\"> <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("		</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Banner Hero -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Categories of The Month -->\r\n");
      out.write("	<section class=\"container py-5\">\r\n");
      out.write("		<div class=\"row text-center pt-3\">\r\n");
      out.write("			<div class=\"col-lg-6 m-auto\">\r\n");
      out.write("				<h1 class=\"h1\">Categories of The Month</h1>\r\n");
      out.write("				<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa\r\n");
      out.write("					qui officia deserunt mollit anim id est laborum.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-12 col-md-4 p-5 mt-3\">\r\n");
      out.write("				<a href=\"#\"><img\r\n");
      out.write("					src=\"templates/web/assets/img/category_img_01.jpg\"\r\n");
      out.write("					class=\"rounded-circle img-fluid border\"></a>\r\n");
      out.write("				<h5 class=\"text-center mt-3 mb-3\">Watches</h5>\r\n");
      out.write("				<p class=\"text-center\">\r\n");
      out.write("					<a class=\"btn btn-success\">Go Shop</a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-12 col-md-4 p-5 mt-3\">\r\n");
      out.write("				<a href=\"#\"><img\r\n");
      out.write("					src=\"templates/web/assets/img/category_img_02.jpg\"\r\n");
      out.write("					class=\"rounded-circle img-fluid border\"></a>\r\n");
      out.write("				<h2 class=\"h5 text-center mt-3 mb-3\">Shoes</h2>\r\n");
      out.write("				<p class=\"text-center\">\r\n");
      out.write("					<a class=\"btn btn-success\">Go Shop</a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-12 col-md-4 p-5 mt-3\">\r\n");
      out.write("				<a href=\"#\"><img\r\n");
      out.write("					src=\"templates/web/assets/img/category_img_03.jpg\"\r\n");
      out.write("					class=\"rounded-circle img-fluid border\"></a>\r\n");
      out.write("				<h2 class=\"h5 text-center mt-3 mb-3\">Accessories</h2>\r\n");
      out.write("				<p class=\"text-center\">\r\n");
      out.write("					<a class=\"btn btn-success\">Go Shop</a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End Categories of The Month -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Featured Product -->\r\n");
      out.write("	<section class=\"bg-light\">\r\n");
      out.write("		<div class=\"container py-5\">\r\n");
      out.write("			<div class=\"row text-center py-3\">\r\n");
      out.write("				<div class=\"col-lg-6 m-auto\">\r\n");
      out.write("					<h1 class=\"h1\">Featured Product</h1>\r\n");
      out.write("					<p>Reprehenderit in voluptate velit esse cillum dolore eu\r\n");
      out.write("						fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("						proident.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<a href=\"shop-single.html\"> <img\r\n");
      out.write("							src=\"templates/web/assets/img/feature_prod_01.jpg\"\r\n");
      out.write("							class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<ul class=\"list-unstyled d-flex justify-content-between\">\r\n");
      out.write("								<li><i class=\"text-warning fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-warning fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-warning fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-muted fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-muted fa fa-star\"></i></li>\r\n");
      out.write("								<li class=\"text-muted text-right\">$240.00</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<a href=\"shop-single.html\"\r\n");
      out.write("								class=\"h2 text-decoration-none text-dark\">Gym Weight</a>\r\n");
      out.write("							<p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("								adipisicing elit. Sunt in culpa qui officia deserunt.</p>\r\n");
      out.write("							<p class=\"text-muted\">Reviews (24)</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<a href=\"shop-single.html\"> <img\r\n");
      out.write("							src=\"templates/web/assets/img/feature_prod_02.jpg\"\r\n");
      out.write("							class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<ul class=\"list-unstyled d-flex justify-content-between\">\r\n");
      out.write("								<li><i class=\"text-warning fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-warning fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-warning fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-muted fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-muted fa fa-star\"></i></li>\r\n");
      out.write("								<li class=\"text-muted text-right\">$480.00</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<a href=\"shop-single.html\"\r\n");
      out.write("								class=\"h2 text-decoration-none text-dark\">Cloud Nike Shoes</a>\r\n");
      out.write("							<p class=\"card-text\">Aenean gravida dignissim finibus. Nullam\r\n");
      out.write("								ipsum diam, posuere vitae pharetra sed, commodo ullamcorper.</p>\r\n");
      out.write("							<p class=\"text-muted\">Reviews (48)</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<a href=\"shop-single.html\"> <img\r\n");
      out.write("							src=\"templates/web/assets/img/feature_prod_03.jpg\"\r\n");
      out.write("							class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<ul class=\"list-unstyled d-flex justify-content-between\">\r\n");
      out.write("								<li><i class=\"text-warning fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-warning fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-warning fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-warning fa fa-star\"></i> <i\r\n");
      out.write("									class=\"text-warning fa fa-star\"></i></li>\r\n");
      out.write("								<li class=\"text-muted text-right\">$360.00</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<a href=\"shop-single.html\"\r\n");
      out.write("								class=\"h2 text-decoration-none text-dark\">Summer Addides\r\n");
      out.write("								Shoes</a>\r\n");
      out.write("							<p class=\"card-text\">Curabitur ac mi sit amet diam luctus\r\n");
      out.write("								porta. Phasellus pulvinar sagittis diam, et scelerisque ipsum\r\n");
      out.write("								lobortis nec.</p>\r\n");
      out.write("							<p class=\"text-muted\">Reviews (74)</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End Featured Product -->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!--  <div class=\"form-group mt-3\" align=\"center\">\r\n");
      out.write("		<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("			onclick=\"window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout'\">LogOut</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"form-group mt-3\" align=\"center\">\r\n");
      out.write("		<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("			onclick=\"window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile'\">Edit</button>\r\n");
      out.write("	</div> -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
